spring.datasource.url=jdbc:postgresql://postgres-user-service:5432/uservice
spring.datasource.username=postgres
spring.datasource.password=mypass
spring.jpa.hibernate.ddl-auto=update

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml
jwt.secret=VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCAxMjM0NTY3ODkw
jwt.expiration=86400000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

internal.api.key=zalupa_ivanycha_mozhem-povtorit_na_berlin_14881337