spring.datasource.url=jdbc:postgresql://localhost:5432/uservice
spring.datasource.username=postgres
spring.datasource.password=mypass
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=true
spring.liquibase.change-log=db.changelog/db.changelog-master.yaml
jwt.secret=VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCAxMjM0NTY3ODkw
jwt.expiration=86400000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer