jwt.secret=${JWT_SECRET:VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCAxMjM0NTY3ODkw}
jwt.expiration=86400000
internal.api.key=${INTERNAL_API_KEY:zalupa_ivanycha_mozhem-povtorit_na_berlin_14881337}
security.allow-internal-api-key=true
security.fail-fast.missing-auth=true
security.fail-fast.invalid-jwt=true
security.entrypoint.json=false
spring.datasource.url=jdbc:postgresql://postgres:5432/uservice
spring.datasource.username=postgres
spring.datasource.password=mypass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer