jwt.secret=${JWT_SECRET:VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCAxMjM0NTY3ODkw}
jwt.expiration=${JWT_EXPIRATION:86400000}


security.jwt.enabled=true
security.allow-internal-api-key=false
security.fail-fast.missing-auth=false
security.fail-fast.invalid-jwt=false
security.entrypoint.json=true
security.internal.api.key=${INTERNAL_API_KEY:zalupa_ivanycha_mozhem-povtorit_na_berlin_14881337}


spring.datasource.url=jdbc:postgresql://postgres:5432/crm_db
spring.datasource.username=postgres
spring.datasource.password=mypass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.kafka.bootstrap-servers=kafka:9092

spring.cloud.openfeign.retry.enabled=true
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.loggerLevel=full

user.service.url=http://user-service:8080

logging.level.com.example.demo.Feign=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.feign=DEBUG