spring.datasource.url=jdbc:postgresql://postgres:5444/crm_db
spring.datasource.username=postgres
spring.datasource.password=mypass
spring.jpa.hibernate.ddl-auto=update


spring.liquibase.enabled=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
jwt.secret=VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCAxMjM0NTY3ODkw
jwt.expiration=86400000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

user.service.url=http://user-service:8080
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.loggerLevel=full


spring.cloud.openfeign.retry.enabled=true


spring.kafka.bootstrap-servers=kafka:9092


logging.level.com.example.demo.Feign=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.feign=DEBUG

security.jwt.enabled=true

internal.api.key=zalupa_ivanycha_mozhem-povtorit_na_berlin_14881337